list = input().split(" ")
print(int(list[0]) + int(list[1]))
print(int(list[0]) - int(list[1]))
print(int(list[0]) * int(list[1]))
print(int(int(list[0]) / int(list[1])))
print(int(list[0]) % int(list[1]))
